spring:
  application:
    name: onlineshop-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  session:
    store-type: redis
  redis:
    port: 6379
    host: 127.0.0.1
server:
  port: 20000
