spring:
  datasource:
    username: root
    password: greedisgood
    url: jdbc:mysql://localhost:3306/onlineshop_oms?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: onlineshop-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    publisher-confirms: true #publisher -> exchange confirm
    publisher-returns: true #exchange -> queue confirm
    template:
      mandatory: true #只要抵达队列，以异步方式优先回调returns
    listener:
      direct:
        acknowledge-mode: manual #设置手动处理消息模式
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 127.0.0.1


onlineshop5:
  thread:
    core-size: 10
    max-size: 100
    keep-alive-time: 10


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000


